### ISSUE TITLE
Erreur 404 sur l'icone de chargement

### ISSUE THREAD

**Issue by DegrangeM** [gvalmont/mathalea_pour_anki#1]
L'icone de chargement ne s'affiche pas car elle pointe sur une erreur 404.

https://github.com/gvalmont/mathalea_pour_anki/blob/main/Basique_modele_du_recto.html#L6

https://github.com/gvalmont/mathalea_pour_anki/blob/main/Basique_modele_du_verso.html#L6

**Comment by gvalmont** [comment]
Bonjour,
Merci du retour.
Je suis désolé du retard de la réponse, assez étonnamment je n'ai reçu aucune notification concernant les issues.
On m'a fait part de ce soucis sur le slack de MathALÉA il y a 2 semaines et j'ai mis une redirection à ce moment là.
Ça devrait donc bien fonctionner maintenant, je t'invite à me prévenir s'il y a encore un soucis.
