### ISSUE TITLE
le iframe s'affiche vide dans anki desktop, et ankidroid

### ISSUE THREAD

**Issue by mgad001** [gvalmont/mathalea_pour_anki#2]
En important le modele de carte dans anki , le contenu de la page de mathalea ne s'affiche pas dans ankidesktop ni dans ankidroid. Seul "Chargement" est affiché. Le code fonctionne avec ankiweb et firefox.
![image](https://user-images.githubusercontent.com/104755898/166202443-990a29cb-a035-4cc5-8178-cf20e9e1f4fd.png)

En créant une carte basique et en insérant le code ci dessous, mathix et coopmaths sont affichés, dans anki desktop et ankidroid mais mathalea et topmaths, non. Dans ce cas aussi, ankiweb/firefox affiche tout.
![image](https://user-images.githubusercontent.com/104755898/166202628-c04ff42e-4de6-413e-9f49-ad92325e4ecf.png)

anki desktop : Version ⁨2.1.44
ankidroid : 2.15.6

`{{Recto}}
<br>
https://mathix.org<br>
<iframe width="420" frameborder="0" height="200" src="https://mathix.org"> </iframe><br>

https://coopmaths.fr<br>
 <iframe width="420" height="315" src="https://coopmaths.fr"> </iframe> <br>

https://coopmaths.fr/mathalea.html?ex=6C10,n=5,i=0&v=recto<br>
 <iframe width="420" height="315" src="https://coopmaths.fr/mathalea.html?ex=6C10,n=5,i=0&v=recto"> </iframe> <br>

https://topmaths.fr<br>
 <iframe width="420" height="315" src="https://topmaths.fr"> </iframe> `

**Comment by gvalmont** [comment]
Bonjour,
Merci du retour.
Je suis désolé du retard de la réponse, assez étonnamment je n'ai reçu aucune notification concernant les issues.
Je viens de faire des tests et pour je ne sais quelle raison, ça ne fonctionne plus sur les versions desktop < 2.1.50.
Je vous invite donc à télécharger une version desktop >= 2.1.50 (la 2.1.53 actuelle fonctionne très bien que ce soit en version Qt5 ou Qt6).
Concernant Ankidroid, je suis moins à l'aise sur cette plateforme pour faire des tests avec les différentes versions mais la version actuelle fonctionne chez moi. Est-ce que vous pouvez vérifier que ça fonctionne bien chez vous aussi ?

**Comment by mgad001** [comment]
Je viens de passer en version 2.1.53, et c'est fonctionnel.
idem pour ankidroid en version 2.15.6.
Un immense merci d'avoir mis au point les modèles de cartes.
Le pouvoir de Anki s'étend aux automatismes, c'est colossal. Mes élèves vont finir par TOUS aimer les maths !!!
